Fix weblate.trans.tests.test_models:ProjectTest failure on subsequent runs.
Check_rename will fail on subsequent runs from same working directory due
to old_path (which is default project path used by many tests) not being removed from previous run:

 Traceback (most recent call last):
  File "/home/vrusinov/workspace/weblate/weblate/trans/tests/test_models.py", line 209, in test_rename
    self.assertFalse(os.path.exists(old_path))
AssertionError: True is not false