Fix icon file handling.
There are 2 issues with the current code:

1. DATA_DIR being ignored for icons (use `settings.STATIC_ROOT`)

2. in case of an exception icon() was called with an empty name.
I could not track where this happens yet, but regardless file reading
should handle all errors.

For example:
```
...
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'xxx.xxx.xxx.xxx'. You may need to add 'xxx.xxx.xxx.xxx' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

...
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/weblate/utils/templatetags/icons.py", line 42, in icon
    with open(os.path.join(PATH, name), "r") as handle:
IsADirectoryError: [Errno 21] Is a directory: '/export/apps/weblate/venv/lib64/python3.6/site-packages/weblate/static/icons/'

During handling of the above exception, another exception occurred:

...
```